version: '3.9'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  wordpress:
    image: wordpress:6.6-php8.2-apache
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_MEMORY_LIMIT', '256M');
    volumes:
      - ../:/var/www/html/wp-content/plugins/svntex2-plugin:delegated
      - wp_data:/var/www/html
    working_dir: /var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin/install.php" ]
      interval: 20s
      timeout: 5s
      retries: 10
volumes:
  db_data:
  wp_data:
