name: Deploy to Hostinger (FTPS)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy plugin via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.211.169
          username: u271371274
          password: ${{ secrets.FTP_PASSWORD }}
          # Deploy into the domain's WordPress plugin folder
          server-dir: /domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin/
          protocol: ftps
          port: 21
          local-dir: ./
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            .git
            .git/**
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/.DS_Store
            **/*.log
            dev/**
            docs/**

      # Static landing deploy removed to let WP render the styled landing as the homepage

      - name: Deploy custom admin portal (outside WP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.211.169
          username: u271371274
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/svntex.com/public_html/admin/
          protocol: ftps
          port: 21
          local-dir: ./custom-admin/
          state-name: .ftp-deploy-sync-state-admin.json
          exclude: |
            **/.git*
            **/.DS_Store

      - name: Deploy admin-v2 (preview, outside WP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.211.169
          username: u271371274
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/svntex.com/public_html/admin-v2/
          protocol: ftps
          port: 21
          local-dir: ./custom-admin-v2/
          state-name: .ftp-deploy-sync-state-admin-v2.json
          exclude: |
            **/.git*
            **/.DS_Store

      - name: Deploy member-v2 (preview, outside WP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.211.169
          username: u271371274
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/svntex.com/public_html/member-v2/
          protocol: ftps
          port: 21
          local-dir: ./custom-member-v2/
          state-name: .ftp-deploy-sync-state-member-v2.json
          exclude: |
            **/.git*
            **/.DS_Store
