name: Deploy to Hostinger (FTPS)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy plugin via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.211.169
          username: u271371274
          password: ${{ secrets.FTP_PASSWORD }}
          # Remote directory relative to your FTP root (Hostinger domain mapping)
          # Deploy into the domain's WordPress plugin folder
          server-dir: /domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin/
          protocol: ftps
          port: 21
          local-dir: ./
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.DS_Store
            **/*.log
            dev/**
            docs/**

      - name: Deploy static landing to domain root
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.211.169
          username: u271371274
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/svntex.com/public_html/
          protocol: ftps
          port: 21
          local-dir: ./custom-landing/
          state-name: .ftp-deploy-sync-state-landing.json
          exclude: |
            **/.git*
            **/.DS_Store

      - name: Deploy custom admin portal
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.211.169
          username: u271371274
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/svntex.com/public_html/admin/
          protocol: ftps
          port: 21
          local-dir: ./custom-admin/
          state-name: .ftp-deploy-sync-state-admin.json
          exclude: |
            **/.git*
            **/.DS_Store
