name: Deploy Plugin via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync main plugin files to Hostinger via SSH
        run: |
          rsync -avz --delete \
          -e "ssh -p 65002 -o StrictHostKeyChecking=no" \
          ./svntex2-plugin/ \
          u271371274@145.79.211.169:/home/u271371274/domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin/

      - name: Sync CSS files to Hostinger css folder via SSH
        run: |
          rsync -avz --delete \
          -e "ssh -p 65002 -o StrictHostKeyChecking=no" \
          ./svntex2-plugin/css/ \
          u271371274@145.79.211.169:/home/u271371274/domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin/css/

