name: Deploy Plugin via SSH

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Prepare rsync include file
        run: |
          cat > include.txt <<'EOF'
          + svntex2-plugin.php
          + hostinger-pipeline-test.php
          + hostinger-deploy-test.php
          + deploy-copilot-test2.php
          + deploy-test-copilot.php
          + test-github-deploy.txt
          + includes/***
          + assets/***
          + views/***
          + README.md
          + CHANGELOG.md
          + TESTING.md
          - *
          EOF
          cat include.txt

      - name: Remote pre-clean (old duplicates)
        run: |
          ssh -p 65002 -o StrictHostKeyChecking=no u271371274@145.79.211.169 "if [ -d /home/u271371274/domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin/svntex2-plugin ]; then rm -rf /home/u271371274/domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin/svntex2-plugin; fi"

      - name: Deploy plugin directory (filtered)
        run: |
          set -euxo pipefail
          echo "Local file snapshot (depth 2)"; find . -maxdepth 2 -type f | sort
          TARGET=/home/u271371274/domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin/
          RSYNC_OPTS="-rlptgoDzv --delete --delete-excluded --checksum --prune-empty-dirs --include-from=include.txt"
          rsync $RSYNC_OPTS -e "ssh -p 65002 -o StrictHostKeyChecking=no" ./ u271371274@145.79.211.169:$TARGET
          ssh -p 65002 -o StrictHostKeyChecking=no u271371274@145.79.211.169 "find $TARGET -type d -exec chmod 755 {} +; find $TARGET -type f -exec chmod 644 {} +"

      - name: List remote target (debug)
        run: |
          ssh -p 65002 -o StrictHostKeyChecking=no u271371274@145.79.211.169 "echo 'Remote top-level:'; ls -1 /home/u271371274/domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin | head; echo 'Recursive sample:'; find /home/u271371274/domains/svntex.com/public_html/wp-content/plugins/svntex2-plugin -maxdepth 3 -type f | head -50"
