name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate required secrets
      run: |
        [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ] || { echo "Missing secret: SSH_PRIVATE_KEY"; exit 1; }
        [ -n "${{ secrets.REMOTE_HOST }}" ] || { echo "Missing secret: REMOTE_HOST"; exit 1; }
        [ -n "${{ secrets.REMOTE_USER }}" ] || { echo "Missing secret: REMOTE_USER"; exit 1; }
        [ -n "${{ secrets.REMOTE_TARGET }}" ] || { echo "Missing secret: REMOTE_TARGET"; exit 1; }

    - name: Deploy to Hostinger
      # Pin to main for latest fixes; inputs on main use camelCase
      uses: easingthemes/ssh-deploy@main
      with:
        sshPrivateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        args: "-rlgoDzvc -i --delete"
        source: "./"
        remoteHost: ${{ secrets.REMOTE_HOST }}
        remoteUser: ${{ secrets.REMOTE_USER }}
        # optional: set via repo secret if non-standard
        # remotePort: ${{ secrets.REMOTE_PORT }}
        target: ${{ secrets.REMOTE_TARGET }}
        exclude: "/.git/, /.github/, /dev/, /docs/, /node_modules/"
